services:
  - type: web
    name: discord-bot-flask
    env: python
    plan: free
    region: ohio
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python AC_MOD_Detector1.1.py
